// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvbSZjE-V9MkJEeB4UsiilO0V2lm2vkEk',
    appId: '1:890733066128:android:245923eef9b376bbbd6515',
    messagingSenderId: '890733066128',
    projectId: 'abhinayaportfolio',
    storageBucket: 'abhinayaportfolio.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdKgWQ6iNAhZNe1b9g_PuNHV7PZ2ATD4E',
    appId: '1:890733066128:web:f7d5324bdd40e2d9bd6515',
    messagingSenderId: '890733066128',
    projectId: 'abhinayaportfolio',
    authDomain: 'abhinayaportfolio.firebaseapp.com',
    storageBucket: 'abhinayaportfolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAma9puJaABjPMeUp32ZEvFUxRhckYkqCs',
    appId: '1:890733066128:ios:6d9519e607457798bd6515',
    messagingSenderId: '890733066128',
    projectId: 'abhinayaportfolio',
    storageBucket: 'abhinayaportfolio.firebasestorage.app',
    iosBundleId: 'com.abhinaya.portfolioapp',
  );

}